#!python

import sys
import os

from octopus.importer.OctopusImporter import OctopusImporter

class BjoernImporter(OctopusImporter):

    def __init__(self):
        self.importerPluginJSON = """{
        "plugin": "radareimporter.jar",
        "class": "bjoern.plugins.radareimporter.RadareImporterPlugin",
        "settings": {
        "projectName": "%s",
        }}
        """

def main(filename):
    importer = BjoernImporter()
    importer.importFile(filename)

def usage():
    print('%s <binary>' % (sys.argv[0]))

if __name__ == '__main__':

    if len(sys.argv) != 2:
        usage()
        exit()

    main(sys.argv[1])
