#!python

import argparse

from bjoern.plugins.use_def_analyser import UseDefAnalyser
from bjoern.plugins.data_dependence import DataDependenceCreator
from octopus.server.orientdb.orientdb_plugin_executor import OrientDBPluginExecutor

parser = argparse.ArgumentParser(description="Value set analysis (VSA) plugin.")
parser.add_argument(
    "-s", "--server-host",
    type=str,
    default="localhost",
    help="set the hostname of the octopus server")

parser.add_argument(
    "-p", "--server-port",
    type=int,
    default=2480,
    help="set the port number of the octopus server")

parser.add_argument(
    "project",
    type=str,
    help="run the plugin for this project")

args = parser.parse_args()

plugin_executor = OrientDBPluginExecutor(args.server_host, args.server_port)
use_def_analyser = UseDefAnalyser(plugin_executor)
use_def_analyser.project = args.project
use_def_analyser.execute()
data_dependence_creator = DataDependenceCreator(plugin_executor)
data_dependence_creator.project = args.project
data_dependence_creator.execute()