#!python

import argparse
import os

from octopus.server.orientdb.orientdb_plugin_executor import OrientDBPluginExecutor
from octopus.server.orientdb.orientdb_project_manager import OrientDBProjectManager

from bjoern.plugins.radare_importer import RadareImporter

parser = argparse.ArgumentParser(description="Octopus importer for Bjoern.")
parser.add_argument(
    "-s", "--server-host",
    type=str,
    default="localhost",
    help="set the hostname of the octopus server")

parser.add_argument(
    "-p", "--server-port",
    type=int,
    default=2480,
    help="set the port number of the octopus server")

parser.add_argument(
    "binary",
    type=argparse.FileType("rb"),
    help="import this executable")

args = parser.parse_args()

project = os.path.basename(args.binary.name)

manager = OrientDBProjectManager(args.server_host, args.server_port)
plugin_executor = OrientDBPluginExecutor(args.server_host, args.server_port)
importer = RadareImporter(plugin_executor)
importer.project = project

manager.create(project)
manager.upload_file(project, args.binary)
importer.execute()
