#!python

import argparse

from bjoern.plugins.alocs import Alocs
from octopus.server.orientdb.orientdb_plugin_executor import OrientDBPluginExecutor

parser = argparse.ArgumentParser(description="Abstract locations (Alocs) plugin.")
parser.add_argument(
    "-s", "--server-host",
    type=str,
    default="localhost",
    help="set the hostname of the octopus server")

parser.add_argument(
    "-p", "--server-port",
    type=int,
    default=2480,
    help="set the port number of the octopus server")

parser.add_argument(
    "project",
    type=str,
    help="run the plugin for this project")

args = parser.parse_args()

plugin_executor = OrientDBPluginExecutor(args.server_host, args.server_port)
plugin = Alocs(plugin_executor)
plugin.project = args.project
plugin.execute()
